apiVersion: v1 
kind: Service
metadata:
  name: postgres-db
  labels:
   name: postgres-service
   app: voting-app-demo
spec: 
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: voting-app-demo