apiVersion: v1
kind: Pod  
metadata: 
  name: worker-pod
  labels:
    name: worker-app
    app: voting-app-demo
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker
      