apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    name: worker-app-deploy 
    app: voting-app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
      app: voting-app-demo
  template:
    metadata: 
      name: worker-pod
      labels:
       name: worker-app
       app: voting-app-demo
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker
      